SORTING_CATEGORIES = [
    {
        "id": "large_plates",
        "number": 1,
        "name": "Large plates",
        "description": "Plates with more than 2 studs along every edge",
        "examples": "4x4, 4x6, 4x8, 6x6, 6x8, 6x10, 8x16 plates, baseplates",
        "color": "#e74c3c",
    },
    {
        "id": "1x_plates",
        "number": 2,
        "name": "1x plates",
        "description": "Plates with 1 stud on the narrowest edge (square studs and round studs)",
        "examples": "1x1, 1x2, 1x3, 1x4, 1x6, 1x8, 1x10, 1x12 plates; round 1x1 plates",
        "color": "#2ecc71",
    },
    {
        "id": "2x_plates",
        "number": 3,
        "name": "2x plates",
        "description": "Plates with 2 studs on the narrowest edge",
        "examples": "2x2, 2x3, 2x4, 2x6, 2x8, 2x10 plates",
        "color": "#3498db",
    },
    {
        "id": "small_bricks",
        "number": 4,
        "name": "Small bricks",
        "description": "Bricks with up to 4 studs on top, including textured bricks",
        "examples": "1x1, 1x2, 1x3, 1x4, 2x2 bricks; textured/masonry bricks",
        "color": "#f39c12",
    },
    {
        "id": "large_bricks",
        "number": 5,
        "name": "Large bricks",
        "description": "Bricks with more than 4 studs on top, including tall bricks",
        "examples": "2x3, 2x4, 2x6, 2x8, 1x6, 1x8 bricks; tall/high bricks",
        "color": "#9b59b6",
    },
    {
        "id": "tiles_panels_jumpers",
        "number": 6,
        "name": "Tiles, panels & jumpers",
        "description": "Flat tiles (no studs on top), panels, jumper plates, and dishes",
        "examples": "1x1, 1x2, 1x4, 2x2 tiles; wall panels; jumper plates; round dishes",
        "color": "#1abc9c",
    },
    {
        "id": "slopes_arches",
        "number": 7,
        "name": "Slopes & arches",
        "description": "Sloped bricks, arches, cheese slopes, and grater pieces",
        "examples": "1x2 slope, 2x3 slope, 1x1 cheese slope, 1x3 arch, curved slopes",
        "color": "#e67e22",
    },
    {
        "id": "snot_cones_barrels",
        "number": 8,
        "name": "SNOT, cones & barrels",
        "description": "SNOT bricks (studs not on top), cones, barrels, and cylinders",
        "examples": "Headlight bricks, bracket pieces, cones, barrels, cylinders, round bricks",
        "color": "#2c3e50",
    },
    {
        "id": "technical_articulated",
        "number": 9,
        "name": "Technical & articulated",
        "description": "Technic bricks, beams, pins, axles, clips, hinges, rails, and rods",
        "examples": "Technic beams, pins, axles, gears, ball joints, clips, hinges, bar pieces, antenna rods",
        "color": "#7f8c8d",
    },
    {
        "id": "minifigs",
        "number": 10,
        "name": "Minifigs",
        "description": "Minifigure parts, hair, hats, animals, and accessories they hold/wear",
        "examples": "Torsos, legs, heads, hair pieces, hats, helmets, capes, animals, weapons, tools",
        "color": "#f1c40f",
    },
    {
        "id": "house_garden_decorated",
        "number": 11,
        "name": "House, garden & decorated",
        "description": "Windows, doors, fences, plants, flowers, trees, and printed/stickered pieces",
        "examples": "Window frames, door frames, fence pieces, flowers, leaves, trees, printed tiles",
        "color": "#27ae60",
    },
    {
        "id": "vehicles_everything_else",
        "number": 12,
        "name": "Vehicles & everything else",
        "description": "Car, helicopter, plane, and boat parts; wheels and tyres; miscellaneous pieces",
        "examples": "Vehicle bases, windshields, wheels, tyres, propellers, boat hulls, anything that doesn't fit other categories",
        "color": "#c0392b",
    },
]
