const CATEGORIES = [
  {
    id: 1,
    name: "Large Plates",
    description: "Plates with more than 2 studs along every edge",
    subcategories: [],
    color: "#E53935",
    icon: "🟥",
  },
  {
    id: 2,
    name: "1x Plates",
    description: "Plates with 1 stud on the narrowest edge",
    subcategories: ["Square studs", "Round studs"],
    color: "#43A047",
    icon: "🟩",
  },
  {
    id: 3,
    name: "2x Plates",
    description: "Plates with 2 studs on the narrowest edge",
    subcategories: [],
    color: "#1E88E5",
    icon: "🟦",
  },
  {
    id: 4,
    name: "Small Bricks",
    description: "Bricks with up to 4 studs on top",
    subcategories: ["Regular", "Textured bricks"],
    color: "#FB8C00",
    icon: "🧱",
  },
  {
    id: 5,
    name: "Large Bricks",
    description: "Bricks with more than 4 studs on top",
    subcategories: ["Regular", "Tall bricks"],
    color: "#8E24AA",
    icon: "🟪",
  },
  {
    id: 6,
    name: "Tiles, Panels & Jumpers",
    description: "Flat smooth pieces, wall panels, offset plates",
    subcategories: ["Tiles", "Panels", "Jumpers & dishes"],
    color: "#00ACC1",
    icon: "⬜",
  },
  {
    id: 7,
    name: "Slopes & Arches",
    description: "Angled and curved top pieces",
    subcategories: ["Slopes & arches", "Cheeses & graters"],
    color: "#F4511E",
    icon: "📐",
  },
  {
    id: 8,
    name: "SNOT, Cones & Barrels",
    description: "Studs-not-on-top pieces, cone shapes, barrel shapes",
    subcategories: ["SNOT (studs not on top)", "Cones", "Barrels"],
    color: "#546E7A",
    icon: "🔶",
  },
  {
    id: 9,
    name: "Technical & Articulated",
    description: "Technic system pieces and connection hardware",
    subcategories: ["Technic", "Clips/hinges/rails/rods"],
    color: "#757575",
    icon: "⚙️",
  },
  {
    id: 10,
    name: "Minifigs",
    description: "Minifigure bodies and accessories",
    subcategories: ["Parts/hair/hats/animals", "Accessories (held & worn items)"],
    color: "#FDD835",
    icon: "🧑",
  },
  {
    id: 11,
    name: "House, Garden & Decorated",
    description: "Architectural, natural, and printed/stickered elements",
    subcategories: ["Windows/doors/fences", "Plants/flowers/trees", "Printed & stickered pieces"],
    color: "#66BB6A",
    icon: "🏠",
  },
  {
    id: 12,
    name: "Vehicles & Everything Else",
    description: "Vehicle parts and anything that doesn't fit above",
    subcategories: ["Car/helicopter/plane/boat parts", "Wheels & tires", "Miscellaneous"],
    color: "#D32F2F",
    icon: "🚗",
  },
];

export default CATEGORIES;
